server:
  port: 8080

spring:
  application:
    name: resume-analyser
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

app:
  max-file-size-mb: 5
  allowed-extensions: pdf,docx,txt
